baseURL: http://trye.io/
languageCode: en-us
title: The data science school that works.
theme: hugo-fresh
googleAnalytics: UA-188253655-1
publishDir: docs
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Please modify directly in hero-body.html
    # Hero subtitle (optional)
    subtitle: Please modify directly in hero-body.html
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/hi.png
  section2:
    title: It's all about engagement
    subtitle: And we get it
    features:
    - title: Well-though mix between self-paced and cohort-based
      text: Hey, let's be honest, we all procrastinate. That's why the average completion rate for MOOCs is 5%. We know how tough it is to motivate ourselves every day to study. That's why we believe in the mix between cohort-based and self-paced learning.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: cohort
    - title: Learning by teaching
      text: >
        Yeah, we heard so many times "learning by doing", "hands-on skills", "practical skills". Well, we think differently. Our vision is to learn by teaching. As Einstein once said, "If you can't explain it to a six year old, you don't understand it yourself.". And, hey, that's fun! Vice versa, if some concepts are difficult, do not hesitate to ask your mates for help.
      icon: teach
    - title: Personalized learning
      text: >
        "Football is cool, but I am more into music. Why your examples are all about football?", "I do not need web-scrapping for my job, I'd rather study SQL in depth", "This concept is too difficult, I just want to understand the main points.". We hear you and we compile the content tailored to your needs. Further, How often do you catch yourself searching the topic in YouTube that you just read in the book? Our perception of various concepts is different -- something is much easier to understand by reading, something -- by watching the video and mimicking the code. That's why we give you the same material in different shapes, and you choose the most appropriate for you.
      icon: ways
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://www.facebook.com/tryeio-110131711547523
      icon: facebook
    - link: https://discord.gg/dt3mc4YjKn
      icon: discord
    - link: https://www.instagram.com/trye_io/
      icon: instagram
    - link: https://www.twitch.tv/tryeofficial
      icon: twitch
    - link: https://github.com/trye-io
      icon: github
    - link: https://twitter.com/trye_io
      icon: twitter
    bulmalogo: false
